protected/modules/admin/controllers/ProveedorController.php
<?php

class ProveedorController extends GxController {

        public function filters() {
                return array('rights');
        }

	public function actionView($id) {
		$this->render('view', array(
			'model' => $this->loadModel($id, 'Proveedor'),
		));
	}
        
        public function actionVer($id) {
		$this->render('ver', array(
			'model' => $this->loadModel($id, 'Proveedor'),
		));
	}
        
        public function actionEditable()
        {
            Yii::import('ext.x-editable.EditableSaver'); //or you can add import 'ext.editable.*' to config
            $es = new EditableSaver('Proveedor');  // 'User' is classname of model to be updated
            $es->update();
        }
        
        public function actionGetTodos(){
            $data= Proveedor::model()->findAll(array('order'=>'id DESC'));
            $data=CHtml::listData($data,'id','nombre');
             foreach($data as $value=>$name)
                {
                    echo CHtml::tag('option',array('value'=>$value),CHtml::encode($name),true);
                 
                }

        }

        public function actionAgregar(){
		
            $model = new Proveedor;
            
		if (isset($_POST['Proveedor'])) {
			$model->setAttributes($_POST['Proveedor']);			
			$model->save();
                        if (Yii::app()->request->isAjaxRequest){
                            echo CJSON::encode(array('status'=>'success','div'=>"Proveedor creado exitosamente"));
                            exit;               
                        }
                        
						
		}		
		if (Yii::app()->request->isAjaxRequest)
                    {
                        echo CJSON::encode(array('status'=>'failure', 'div'=>$this->renderPartial('_agregar', array('model' => $model,),true)));
                        exit;               
                    }
	}
        
	public function actionCreate() {
		$model = new Proveedor;

		$this->performAjaxValidation($model, 'proveedor-form');

		if (isset($_POST['Proveedor'])) {
			$model->setAttributes($_POST['Proveedor']);

			if ($model->save()) {
				if (Yii::app()->getRequest()->getIsAjaxRequest())
					Yii::app()->end();
				else
					$this->redirect(array('view', 'id' => $model->id));
			}
		}

		$this->render('create', array( 'model' => $model));
	}
        
        public function actionCrear() {
		$model = new Proveedor;

		$this->performAjaxValidation($model, 'proveedor-form');

		if (isset($_POST['Proveedor'])) {
			$model->setAttributes($_POST['Proveedor']);

			if ($model->save()) {
				if (Yii::app()->getRequest()->getIsAjaxRequest())
					Yii::app()->end();
				else
					$this->redirect(array('ver', 'id' => $model->id));
			}
		}

		$this->render('crear', array( 'model' => $model));
	}

	public function actionUpdate($id) {
		$model = $this->loadModel($id, 'Proveedor');

		$this->performAjaxValidation($model, 'proveedor-form');

		if (isset($_POST['Proveedor'])) {
			$model->setAttributes($_POST['Proveedor']);

			if ($model->save()) {
				$this->redirect(array('view', 'id' => $model->id));
			}
		}

		$this->render('update', array(
				'model' => $model,
				));
	}
        
        public function actionActualizar($id) {
		$model = $this->loadModel($id, 'Proveedor');

		$this->performAjaxValidation($model, 'proveedor-form');

		if (isset($_POST['Proveedor'])) {
			$model->setAttributes($_POST['Proveedor']);

			if ($model->save()) {
				$this->redirect(array('ver', 'id' => $model->id));
			}
		}

		$this->render('actualizar', array(
				'model' => $model,
				));
	}

	public function actionDelete($id) {
		if (Yii::app()->getRequest()->getIsPostRequest()) {
			$this->loadModel($id, 'Proveedor')->delete();

			if (!Yii::app()->getRequest()->getIsAjaxRequest())
				$this->redirect(array('admin'));
		} else
			throw new CHttpException(400, Yii::t('app', 'Your request is invalid.'));
	}

	public function actionIndex() {
		$dataProvider = new CActiveDataProvider('Proveedor');
		$this->render('index', array(
			'dataProvider' => $dataProvider,
		));
	}

	public function actionAdmin() {
                $session = new CHttpSession;
                $session->open();
		$model = new Proveedor('search');
		$model->unsetAttributes();

		if (isset($_GET['Proveedor'])){
			$model->setAttributes($_GET['Proveedor']);
                }

                $session['Proveedor_model_search'] = $model;
                
		$this->render('admin', array(
			'model' => $model,
		));
	}
        
        public function actionVerTodos() {
                $session = new CHttpSession;
                $session->open();
		$model = new Proveedor('search');
		$model->unsetAttributes();

		if (isset($_GET['Proveedor'])){
			$model->setAttributes($_GET['Proveedor']);
                }

                $session['Proveedor_model_search'] = $model;
                
		$this->render('verTodos', array(
			'model' => $model,
		));
	}
        
        public function behaviors()
        {
            return array(
                'eexcelview'=>array(
                    'class'=>'ext.eexcelview.EExcelBehavior',
                ),
            );
        }
        
        public function actionGenerateExcel()
	{	   
             $session=new CHttpSession;
             $session->open();
             if(isset($session['Proveedor_model_search']))
               {
                $model = $session['Proveedor_model_search'];
                $model = Proveedor::model()->findAll($model->search()->criteria);
               }
               else
                 $model = Proveedor::model()->findAll();
             
             $this->toExcel($model, array('id', 'rut', 'nombre'), date('Y-m-d-H-i-s'), array(), 'Excel5');
	}
        
        public function actionGeneratePdf() 
	{
             $session=new CHttpSession;
             $session->open();
             if(isset($session['Proveedor_model_search']))
               {
                $model = $session['Proveedor_model_search'];
                $model = Proveedor::model()->findAll($model->search()->criteria);
               }
               else
                 $model = Proveedor::model()->findAll();
             
             $this->toExcel($model, array('id', 'rut', 'nombre'), date('Y-m-d-H-i-s'), array(), 'PDF');
	}
}

protected/modules/admin/controllers/ProyectoController.php
<?php

class ProyectoController extends GxController {

        public function filters() {
                return array('rights');
        }

	public function actionView($id) {
		$this->render('view', array(
			'model' => $this->loadModel($id, 'Proyecto'),
		));
	}
        public function actionEditable()
        {
            Yii::import('ext.x-editable.EditableSaver'); //or you can add import 'ext.editable.*' to config
            $es = new EditableSaver('Proyecto');  // 'User' is classname of model to be updated
            $es->update();
        }

	public function actionCreate() {
		$model = new Proyecto;

		$this->performAjaxValidation($model, 'proyecto-form');

		if (isset($_POST['Proyecto'])) {
			$model->setAttributes($_POST['Proyecto']);

			if ($model->save()) {
				if (Yii::app()->getRequest()->getIsAjaxRequest())
					Yii::app()->end();
				else
					$this->redirect(array('view', 'id' => $model->id));
			}
		}

		$this->render('create', array( 'model' => $model));
	}

	public function actionUpdate($id) {
		$model = $this->loadModel($id, 'Proyecto');

		$this->performAjaxValidation($model, 'proyecto-form');

		if (isset($_POST['Proyecto'])) {
			$model->setAttributes($_POST['Proyecto']);

			if ($model->save()) {
				$this->redirect(array('view', 'id' => $model->id));
			}
		}

		$this->render('update', array(
				'model' => $model,
				));
	}

	public function actionDelete($id) {
		if (Yii::app()->getRequest()->getIsPostRequest()) {
			$this->loadModel($id, 'Proyecto')->delete();

			if (!Yii::app()->getRequest()->getIsAjaxRequest())
				$this->redirect(array('admin'));
		} else
			throw new CHttpException(400, Yii::t('app', 'Your request is invalid.'));
	}

	public function actionIndex() {
		$dataProvider = new CActiveDataProvider('Proyecto');
		$this->render('index', array(
			'dataProvider' => $dataProvider,
		));
	}

	public function actionAdmin() {
                $session = new CHttpSession;
                $session->open();
		$model = new Proyecto('search');
		$model->unsetAttributes();

		if (isset($_GET['Proyecto'])){
			$model->setAttributes($_GET['Proyecto']);
                }

                $session['Proyecto_model_search'] = $model;
                
		$this->render('admin', array(
			'model' => $model,
		));
	}
        
        public function behaviors()
        {
            return array(
                'eexcelview'=>array(
                    'class'=>'ext.eexcelview.EExcelBehavior',
                ),
            );
        }
        
        public function actionGenerateExcel()
	{	   
             $session=new CHttpSession;
             $session->open();
             if(isset($session['Proyecto_model_search']))
               {
                $model = $session['Proyecto_model_search'];
                $model = Proyecto::model()->findAll($model->search()->criteria);
               }
               else
                 $model = Proyecto::model()->findAll();
             
             $this->toExcel($model, array('id', 'rrhh', 'centroCosto', 'nombre', 'descripcion', 'archivo', 'contrato', 'comuna', 'region'), date('Y-m-d-H-i-s'), array(), 'Excel5');
	}
        
        public function actionGeneratePdf() 
	{
             $session=new CHttpSession;
             $session->open();
             if(isset($session['Proyecto_model_search']))
               {
                $model = $session['Proyecto_model_search'];
                $model = Proyecto::model()->findAll($model->search()->criteria);
               }
               else
                 $model = Proyecto::model()->findAll();
             
             $this->toExcel($model, array('id', 'rrhh', 'centroCosto', 'nombre', 'descripcion', 'archivo', 'contrato', 'comuna', 'region'), date('Y-m-d-H-i-s'), array(), 'PDF');
	}
}

protected/modules/admin/controllers/RendicionController.php
<?php

class RendicionController extends GxController {

        public function filters() {
                return array('rights');
        }

	public function actionView($id) {
		$this->render('view', array(
			'model' => $this->loadModel($id, 'Rendicion'),
		));
	}
        
        public function actionEditable()
        {
            Yii::import('ext.x-editable.EditableSaver'); //or you can add import 'ext.editable.*' to config
            $es = new EditableSaver('Rendicion');  // 'User' is classname of model to be updated
            $es->update();
        }

	public function actionCreate() {
		$model = new Rendicion;

		$this->performAjaxValidation($model, 'rendicion-form');

		if (isset($_POST['Rendicion'])) {
			$model->setAttributes($_POST['Rendicion']);

			if ($model->save()) {
				if (Yii::app()->getRequest()->getIsAjaxRequest())
					Yii::app()->end();
				else
					$this->redirect(array('view', 'id' => $model->id));
			}
		}

		$this->render('create', array( 'model' => $model));
	}

	public function actionUpdate($id) {
		$model = $this->loadModel($id, 'Rendicion');

		$this->performAjaxValidation($model, 'rendicion-form');

		if (isset($_POST['Rendicion'])) {
			$model->setAttributes($_POST['Rendicion']);

			if ($model->save()) {
				$this->redirect(array('view', 'id' => $model->id));
			}
		}

		$this->render('update', array(
				'model' => $model,
				));
	}

	public function actionDelete($id) {
		if (Yii::app()->getRequest()->getIsPostRequest()) {
			$this->loadModel($id, 'Rendicion')->delete();

			if (!Yii::app()->getRequest()->getIsAjaxRequest())
				$this->redirect(array('admin'));
		} else
			throw new CHttpException(400, Yii::t('app', 'Your request is invalid.'));
	}

	public function actionIndex() {
		$dataProvider = new CActiveDataProvider('Rendicion');
		$this->render('index', array(
			'dataProvider' => $dataProvider,
		));
	}

	public function actionAdmin() {
                $session = new CHttpSession;
                $session->open();
		$model = new Rendicion('search');
		$model->unsetAttributes();

		if (isset($_GET['Rendicion'])){
			$model->setAttributes($_GET['Rendicion']);
                }

                $session['Rendicion_model_search'] = $model;
                
		$this->render('admin', array(
			'model' => $model,
		));
	}
        
        public function behaviors()
        {
            return array(
                'eexcelview'=>array(
                    'class'=>'ext.eexcelview.EExcelBehavior',
                ),
            );
        }
        
        public function actionGenerateExcel()
	{	   
             $session=new CHttpSession;
             $session->open();
             if(isset($session['Rendicion_model_search']))
               {
                $model = $session['Rendicion_model_search'];
                $model = Rendicion::model()->findAll($model->search()->criteria);
               }
               else
                 $model = Rendicion::model()->findAll();
             
             $this->toExcel($model, array('id', 'user', 'emision', 'asignacion', 'fecha', 'comuna', 'region', 'tipo_pago', 'total_entrada', 'total_salida', 'total_saldo', 'observacion', 'estado'), date('Y-m-d-H-i-s'), array(), 'Excel5');
	}
        
        public function actionGeneratePdf() 
	{
             $session=new CHttpSession;
             $session->open();
             if(isset($session['Rendicion_model_search']))
               {
                $model = $session['Rendicion_model_search'];
                $model = Rendicion::model()->findAll($model->search()->criteria);
               }
               else
                 $model = Rendicion::model()->findAll();
             
             $this->toExcel($model, array('id', 'user', 'emision', 'asignacion', 'fecha', 'comuna', 'region', 'tipo_pago', 'total_entrada', 'total_salida', 'total_saldo', 'observacion', 'estado'), date('Y-m-d-H-i-s'), array(), 'PDF');
	}
}

protected/modules/admin/views/itemRendicion/_form.php
<div class="form">

    
<?php $this->widget('ext.EChosen.EChosen', array('target' => 'select')); ?>
<?php $form = $this->beginWidget('GxActiveForm', array(
	'id' => 'item-rendicion-form',
	'enableAjaxValidation' => true,
));
?>

	<p class="note">
		<?php echo Yii::t('app', 'Fields with'); ?> <span class="required">*</span> <?php echo Yii::t('app', 'are required'); ?>.
	</p>

	<?php echo $form->errorSummary($model); ?>

		<div class="row">
		<?php echo $form->labelEx($model,'proveedor_id'); ?>
		<?php echo $form->dropDownList($model, 'proveedor_id', GxHtml::listDataEx(Proveedor::model()->findAllAttributes(null, true))); ?>
		<?php echo $form->error($model,'proveedor_id'); ?>
		</div><!-- row -->
		<div class="row">
		<?php echo $form->labelEx($model,'cuenta_contable_id'); ?>
		<?php echo $form->dropDownList($model, 'cuenta_contable_id', GxHtml::listDataEx(CuentaContable::model()->findAllAttributes(null, true))); ?>
		<?php echo $form->error($model,'cuenta_contable_id'); ?>
		</div><!-- row -->
		<div class="row">
		<?php echo $form->labelEx($model,'cuenta_especifica_id'); ?>
		<?php echo $form->dropDownList($model, 'cuenta_especifica_id', GxHtml::listDataEx(CuentaEspecifica::model()->findAllAttributes(null, true))); ?>
		<?php echo $form->error($model,'cuenta_especifica_id'); ?>
		</div><!-- row -->
		<div class="row">
		<?php echo $form->labelEx($model,'rendicion_id'); ?>
		<?php echo $form->dropDownList($model, 'rendicion_id', GxHtml::listDataEx(Rendicion::model()->findAllAttributes(null, true))); ?>
		<?php echo $form->error($model,'rendicion_id'); ?>
		</div><!-- row -->
		<div class="row">
		<?php echo $form->labelEx($model,'proyecto_id'); ?>
		<?php echo $form->dropDownList($model, 'proyecto_id', GxHtml::listDataEx(Proyecto::model()->findAllAttributes(null, true))); ?>
		<?php echo $form->error($model,'proyecto_id'); ?>
		</div><!-- row -->
		<div class="row">
		<?php echo $form->labelEx($model,'tipo_documento'); ?>
		<?php echo $form->textField($model, 'tipo_documento', array('maxlength' => 100)); ?>
		<?php echo $form->error($model,'tipo_documento'); ?>
		</div><!-- row -->
		<div class="row">
		<?php echo $form->labelEx($model,'numero_documento'); ?>
		<?php echo $form->textField($model, 'numero_documento', array('maxlength' => 100)); ?>
		<?php echo $form->error($model,'numero_documento'); ?>
		</div><!-- row -->
		<div class="row">
		<?php echo $form->labelEx($model,'fecha'); ?>
		<?php $form->widget('zii.widgets.jui.CJuiDatePicker', array(
			'model' => $model,
			'attribute' => 'fecha',
			'value' => $model->fecha,
                        'language' => Yii::app()->language,    
			'options' => array(
				'showButtonPanel' => true,
                                'changeMonth' => true,
				'changeYear' => true,
				'dateFormat' => 'yy-mm-dd',
				),
			));
; ?>
		<?php echo $form->error($model,'fecha'); ?>
		</div><!-- row -->
		<div class="row">
		<?php echo $form->labelEx($model,'mes'); ?>
		<?php echo $form->textField($model, 'mes', array('maxlength' => 45)); ?>
		<?php echo $form->error($model,'mes'); ?>
		</div><!-- row -->
		<div class="row">
		<?php echo $form->labelEx($model,'agno'); ?>
		<?php echo $form->textField($model, 'agno', array('maxlength' => 45)); ?>
		<?php echo $form->error($model,'agno'); ?>
		</div><!-- row -->
		<div class="row">
		<?php echo $form->labelEx($model,'monto'); ?>
		<?php echo $form->textField($model, 'monto'); ?>
		<?php echo $form->error($model,'monto'); ?>
		</div><!-- row -->


<?php
echo GxHtml::submitButton(Yii::t('app', 'Save'), array('onClick' => "this.disabled=true;this.value='".Yii::t('app', 'Enviando')."';this.form.submit();"));
$this->endWidget();
?>
</div><!-- form -->

protected/modules/admin/views/itemRendicion/_search.php
<?php $this->widget('ext.EChosen.EChosen' ); ?><div class="wide form">

<?php $form = $this->beginWidget('bootstrap.widgets.TbActiveForm', array(
        'id'=>'search-item-rendicion-form',
	'action' => Yii::app()->createUrl($this->route),
	'method' => 'get',
)); ?>

	<div class="row">
		<?php echo $form->label($model, 'id'); ?>
		<?php echo $form->textField($model, 'id'); ?>
	</div>
                
	<div class="row">
		<?php echo $form->label($model, 'proveedor_id'); ?>
		<?php echo $form->dropDownList($model, 'proveedor_id', GxHtml::listDataEx(Proveedor::model()->findAllAttributes(null, true)), array('prompt' => Yii::t('app', 'All'))); ?>
	</div>
                
	<div class="row">
		<?php echo $form->label($model, 'cuenta_contable_id'); ?>
		<?php echo $form->dropDownList($model, 'cuenta_contable_id', GxHtml::listDataEx(CuentaContable::model()->findAllAttributes(null, true)), array('prompt' => Yii::t('app', 'All'))); ?>
	</div>
                
	<div class="row">
		<?php echo $form->label($model, 'cuenta_especifica_id'); ?>
		<?php echo $form->dropDownList($model, 'cuenta_especifica_id', GxHtml::listDataEx(CuentaEspecifica::model()->findAllAttributes(null, true)), array('prompt' => Yii::t('app', 'All'))); ?>
	</div>
                
	<div class="row">
		<?php echo $form->label($model, 'rendicion_id'); ?>
		<?php echo $form->dropDownList($model, 'rendicion_id', GxHtml::listDataEx(Rendicion::model()->findAllAttributes(null, true)), array('prompt' => Yii::t('app', 'All'))); ?>
	</div>
                
	<div class="row">
		<?php echo $form->label($model, 'proyecto_id'); ?>
		<?php echo $form->dropDownList($model, 'proyecto_id', GxHtml::listDataEx(Proyecto::model()->findAllAttributes(null, true)), array('prompt' => Yii::t('app', 'All'))); ?>
	</div>
                
	<div class="row">
		<?php echo $form->label($model, 'tipo_documento'); ?>
		<?php echo $form->textField($model, 'tipo_documento', array('maxlength' => 100)); ?>
	</div>
                
	<div class="row">
		<?php echo $form->label($model, 'numero_documento'); ?>
		<?php echo $form->textField($model, 'numero_documento', array('maxlength' => 100)); ?>
	</div>
                
	<div class="row">
		<?php echo $form->label($model, 'fecha'); ?>
		<?php $form->widget('zii.widgets.jui.CJuiDatePicker', array(
			'model' => $model,
			'attribute' => 'fecha',
			'value' => $model->fecha,
                        'language' => Yii::app()->language,    
			'options' => array(
				'showButtonPanel' => true,
                                'changeMonth' => true,
				'changeYear' => true,
				'dateFormat' => 'yy-mm-dd',
				),
			));
; ?>
	</div>
                	<div class="row">
                <?php echo $form->label($model, 'fecha_inicio'); ?>
                <?php $form->widget('zii.widgets.jui.CJuiDatePicker', array(
			'model' => $model,
			'attribute' => 'fecha_inicio',
			'value' => $model->fecha_inicio,
                        'language' => Yii::app()->language,    
			'options' => array(
				'showButtonPanel' => true,
                                'changeMonth' => true,
				'changeYear' => true,
				'dateFormat' => 'yy-mm-dd',
				),
			));
; ?>
	</div>
	<div class="row">
                <?php echo $form->label($model, 'fecha_termino'); ?>
    
                <?php $form->widget('zii.widgets.jui.CJuiDatePicker', array(
			'model' => $model,
			'attribute' => 'fecha_termino',
			'value' => $model->fecha_termino,
                        'language' => Yii::app()->language,    
			'options' => array(
				'showButtonPanel' => true,
                                'changeMonth' => true,
				'changeYear' => true,
				'dateFormat' => 'yy-mm-dd',
				),
			));
; ?>
	</div>
                
	<div class="row">
		<?php echo $form->label($model, 'mes'); ?>
		<?php echo $form->textField($model, 'mes', array('maxlength' => 45)); ?>
	</div>
                
	<div class="row">
		<?php echo $form->label($model, 'agno'); ?>
		<?php echo $form->textField($model, 'agno', array('maxlength' => 45)); ?>
	</div>
                
	<div class="row">
		<?php echo $form->label($model, 'monto'); ?>
		<?php echo $form->textField($model, 'monto'); ?>
	</div>
                
	<div class="row buttons">
		<?php $this->widget('bootstrap.widgets.TbButton', array('buttonType'=>'submit', 'label'=>Yii::t('app', 'Search'), 'icon'=>'search'));?>
		<?php $this->widget('bootstrap.widgets.TbButton', array('buttonType'=>'button', 'label'=>Yii::t('app', 'Reset'), 'icon'=>'icon-remove-sign', 'htmlOptions'=>array('class'=>'btnreset btn-small')));?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->
<script>
     $(".btnreset").click(function(){
             $(":input","#search-item-rendicion-form").each(function() {
             var type = this.type;
             var tag = this.tagName.toLowerCase(); // normalize case
             if (type == "text" || type == "password" || tag == "textarea") this.value = "";
             else if (type == "checkbox" || type == "radio") this.checked = false;
             else if (tag == "select") this.selectedIndex = "";
       });
     });
</script>


protected/modules/admin/views/itemRendicion/create.php
<?php

$this->breadcrumbs = array(
	$model->label(2) => array('index'),
	Yii::t('app', 'Create'),
);

$this->menu = array(
	array('label'=>Yii::t('app', 'List') . ' ' . $model->label(2), 'url' => array('index')),
	array('label'=>Yii::t('app', 'Manage') . ' ' . $model->label(2), 'url' => array('admin')),
);
?>

<h1><?php echo Yii::t('app', 'Create') . ' ' . GxHtml::encode($model->label()); ?></h1>

<?php
$this->renderPartial('_form', array(
		'model' => $model,
		'buttons' => 'create'));
?>

protected/modules/admin/views/itemRendicion/index.php
<?php

$this->breadcrumbs = array(
	ItemRendicion::label(2),
	Yii::t('app', 'Index'),
);

$this->menu = array(
	array('label'=>Yii::t('app', 'Create') . ' ' . ItemRendicion::label(), 'url' => array('create')),
	array('label'=>Yii::t('app', 'Manage') . ' ' . ItemRendicion::label(2), 'url' => array('admin')),
);
?>

<h1><?php echo GxHtml::encode(ItemRendicion::label(2)); ?></h1>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
)); 

protected/modules/admin/views/itemRendicion/view.php
<?php

$this->breadcrumbs = array(
	$model->label(2) => array('index'),
	GxHtml::valueEx($model),
);

$this->menu=array(
	array('label'=>Yii::t('app', 'List') . ' ' . $model->label(2), 'url'=>array('index')),
	array('label'=>Yii::t('app', 'Create') . ' ' . $model->label(), 'url'=>array('create')),
	array('label'=>Yii::t('app', 'Update') . ' ' . $model->label(), 'url'=>array('update', 'id' => $model->id)),
	array('label'=>Yii::t('app', 'Delete') . ' ' . $model->label(), 'url'=>'#', 'linkOptions' => array('submit' => array('delete', 'id' => $model->id), 'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>Yii::t('app', 'Manage') . ' ' . $model->label(2), 'url'=>array('admin')),
);
?>

<h1><?php echo Yii::t('app', 'View') . ' ' . GxHtml::encode($model->label()) . ' ' . GxHtml::encode(GxHtml::valueEx($model)); ?></h1>

<?php $this->widget('bootstrap.widgets.TbDetailView', array(
	'data' => $model,
	'attributes' => array(
'id',
array(
			'name' => 'proveedor',
			'type' => 'raw',
			'value' => $model->proveedor !== null ? GxHtml::link(GxHtml::encode(GxHtml::valueEx($model->proveedor)), array('proveedor/view', 'id' => GxActiveRecord::extractPkValue($model->proveedor, true))) : null,
			),
array(
			'name' => 'cuentaContable',
			'type' => 'raw',
			'value' => $model->cuentaContable !== null ? GxHtml::link(GxHtml::encode(GxHtml::valueEx($model->cuentaContable)), array('cuentaContable/view', 'id' => GxActiveRecord::extractPkValue($model->cuentaContable, true))) : null,
			),
array(
			'name' => 'cuentaEspecifica',
			'type' => 'raw',
			'value' => $model->cuentaEspecifica !== null ? GxHtml::link(GxHtml::encode(GxHtml::valueEx($model->cuentaEspecifica)), array('cuentaEspecifica/view', 'id' => GxActiveRecord::extractPkValue($model->cuentaEspecifica, true))) : null,
			),
array(
			'name' => 'rendicion',
			'type' => 'raw',
			'value' => $model->rendicion !== null ? GxHtml::link(GxHtml::encode(GxHtml::valueEx($model->rendicion)), array('rendicion/view', 'id' => GxActiveRecord::extractPkValue($model->rendicion, true))) : null,
			),
array(
			'name' => 'proyecto',
			'type' => 'raw',
			'value' => $model->proyecto !== null ? GxHtml::link(GxHtml::encode(GxHtml::valueEx($model->proyecto)), array('proyecto/view', 'id' => GxActiveRecord::extractPkValue($model->proyecto, true))) : null,
			),
'tipo_documento',
'numero_documento',
'fecha',
'mes',
'agno',
            array(
                'name' => 'Monto',
                'value' => Yii::app()->format->formatNumber($model->monto),
            ),

	),
)); ?>