protected/modules/admin/controllers/EmisionController.php
<?php

class EmisionController extends GxController {

        public function filters() {
                return array('rights');
        }

	public function actionView($id) {
		$this->render('view', array(
			'model' => $this->loadModel($id, 'Emision'),
		));
	}
        public function actionEditable()
        {
            Yii::import('ext.x-editable.EditableSaver'); //or you can add import 'ext.editable.*' to config
            $es = new EditableSaver('Emision');  // 'User' is classname of model to be updated
            $es->update();
        }

	public function actionCreate() {
		$model = new Emision;

		$this->performAjaxValidation($model, 'emision-form');

		if (isset($_POST['Emision'])) {
			$model->setAttributes($_POST['Emision']);

			if ($model->save()) {
				if (Yii::app()->getRequest()->getIsAjaxRequest())
					Yii::app()->end();
				else
					$this->redirect(array('view', 'id' => $model->id));
			}
		}

		$this->render('create', array( 'model' => $model));
	}

	public function actionUpdate($id) {
		$model = $this->loadModel($id, 'Emision');

		$this->performAjaxValidation($model, 'emision-form');

		if (isset($_POST['Emision'])) {
			$model->setAttributes($_POST['Emision']);

			if ($model->save()) {
				$this->redirect(array('view', 'id' => $model->id));
			}
		}

		$this->render('update', array(
				'model' => $model,
				));
	}

	public function actionDelete($id) {
		if (Yii::app()->getRequest()->getIsPostRequest()) {
			$this->loadModel($id, 'Emision')->delete();

			if (!Yii::app()->getRequest()->getIsAjaxRequest())
				$this->redirect(array('admin'));
		} else
			throw new CHttpException(400, Yii::t('app', 'Your request is invalid.'));
	}

	public function actionIndex() {
		$dataProvider = new CActiveDataProvider('Emision');
		$this->render('index', array(
			'dataProvider' => $dataProvider,
		));
	}

	public function actionAdmin() {
                $session = new CHttpSession;
                $session->open();
		$model = new Emision('search');
		$model->unsetAttributes();

		if (isset($_GET['Emision'])){
			$model->setAttributes($_GET['Emision']);
                }

                $session['Emision_model_search'] = $model;
                
		$this->render('admin', array(
			'model' => $model,
		));
	}
        
        public function behaviors()
        {
            return array(
                'eexcelview'=>array(
                    'class'=>'ext.eexcelview.EExcelBehavior',
                ),
            );
        }
        
        public function actionGenerateExcel()
	{	   
             $session=new CHttpSession;
             $session->open();
             if(isset($session['Emision_model_search']))
               {
                $model = $session['Emision_model_search'];
                $model = Emision::model()->findAll($model->search()->criteria);
               }
               else
                 $model = Emision::model()->findAll();
             
             $this->toExcel($model, array('id', 'user', 'proveedor', 'proyecto', 'solicitud', 'ciudad', 'fecha', 'concepto', 'total_debe', 'total_haber', 'cuenta', 'tipo_solicitud', 'numero_cheque', 'observaciones', 'estado'), date('Y-m-d-H-i-s'), array(), 'Excel5');
	}
        
        public function actionGeneratePdf() 
	{
             $session=new CHttpSession;
             $session->open();
             if(isset($session['Emision_model_search']))
               {
                $model = $session['Emision_model_search'];
                $model = Emision::model()->findAll($model->search()->criteria);
               }
               else
                 $model = Emision::model()->findAll();
             
             $this->toExcel($model, array('id', 'user', 'proveedor', 'proyecto', 'solicitud', 'ciudad', 'fecha', 'concepto', 'total_debe', 'total_haber', 'cuenta', 'tipo_solicitud', 'numero_cheque', 'observaciones', 'estado'), date('Y-m-d-H-i-s'), array(), 'PDF');
	}
}

protected/modules/admin/controllers/IngresoController.php
<?php

class IngresoController extends GxController {

        public function filters() {
                return array('rights');
        }

	public function actionView($id) {
		$this->render('view', array(
			'model' => $this->loadModel($id, 'Ingreso'),
		));
	}
        
        public function actionEditable()
        {
            Yii::import('ext.x-editable.EditableSaver'); //or you can add import 'ext.editable.*' to config
            $es = new EditableSaver('Ingreso');  // 'User' is classname of model to be updated
            $es->update();
        }

	public function actionCreate() {
		$model = new Ingreso;

		$this->performAjaxValidation($model, 'ingreso-form');

		if (isset($_POST['Ingreso'])) {
			$model->setAttributes($_POST['Ingreso']);

			if ($model->save()) {
				if (Yii::app()->getRequest()->getIsAjaxRequest())
					Yii::app()->end();
				else
					$this->redirect(array('view', 'id' => $model->id));
			}
		}

		$this->render('create', array( 'model' => $model));
	}

	public function actionUpdate($id) {
		$model = $this->loadModel($id, 'Ingreso');

		$this->performAjaxValidation($model, 'ingreso-form');

		if (isset($_POST['Ingreso'])) {
			$model->setAttributes($_POST['Ingreso']);

			if ($model->save()) {
				$this->redirect(array('view', 'id' => $model->id));
			}
		}

		$this->render('update', array(
				'model' => $model,
				));
	}

	public function actionDelete($id) {
		if (Yii::app()->getRequest()->getIsPostRequest()) {
			$this->loadModel($id, 'Ingreso')->delete();

			if (!Yii::app()->getRequest()->getIsAjaxRequest())
				$this->redirect(array('admin'));
		} else
			throw new CHttpException(400, Yii::t('app', 'Your request is invalid.'));
	}

	public function actionIndex() {
		$dataProvider = new CActiveDataProvider('Ingreso');
		$this->render('index', array(
			'dataProvider' => $dataProvider,
		));
	}

	public function actionAdmin() {
                $session = new CHttpSession;
                $session->open();
		$model = new Ingreso('search');
		$model->unsetAttributes();

		if (isset($_GET['Ingreso'])){
			$model->setAttributes($_GET['Ingreso']);
                }

                $session['Ingreso_model_search'] = $model;
                
		$this->render('admin', array(
			'model' => $model,
		));
	}
        
        public function behaviors()
        {
            return array(
                'eexcelview'=>array(
                    'class'=>'ext.eexcelview.EExcelBehavior',
                ),
            );
        }
        
        public function actionGenerateExcel()
	{	   
             $session=new CHttpSession;
             $session->open();
             if(isset($session['Ingreso_model_search']))
               {
                $model = $session['Ingreso_model_search'];
                $model = Ingreso::model()->findAll($model->search()->criteria);
               }
               else
                 $model = Ingreso::model()->findAll();
             
             $this->toExcel($model, array('id', 'proyecto', 'tipoIngreso', 'financiamiento', 'fecha', 'monto', 'observaciones'), date('Y-m-d-H-i-s'), array(), 'Excel5');
	}
        
        public function actionGeneratePdf() 
	{
             $session=new CHttpSession;
             $session->open();
             if(isset($session['Ingreso_model_search']))
               {
                $model = $session['Ingreso_model_search'];
                $model = Ingreso::model()->findAll($model->search()->criteria);
               }
               else
                 $model = Ingreso::model()->findAll();
             
             $this->toExcel($model, array('id', 'proyecto', 'tipoIngreso', 'financiamiento', 'fecha', 'monto', 'observaciones'), date('Y-m-d-H-i-s'), array(), 'PDF');
	}
}

protected/modules/admin/controllers/ProyectoController.php
<?php

class ProyectoController extends GxController {

        public function filters() {
                return array('rights');
        }

	public function actionView($id) {
		$this->render('view', array(
			'model' => $this->loadModel($id, 'Proyecto'),
		));
	}
        public function actionEditable()
        {
            Yii::import('ext.x-editable.EditableSaver'); //or you can add import 'ext.editable.*' to config
            $es = new EditableSaver('Proyecto');  // 'User' is classname of model to be updated
            $es->update();
        }

	public function actionCreate() {
		$model = new Proyecto;

		$this->performAjaxValidation($model, 'proyecto-form');

		if (isset($_POST['Proyecto'])) {
			$model->setAttributes($_POST['Proyecto']);

			if ($model->save()) {
				if (Yii::app()->getRequest()->getIsAjaxRequest())
					Yii::app()->end();
				else
					$this->redirect(array('view', 'id' => $model->id));
			}
		}

		$this->render('create', array( 'model' => $model));
	}

	public function actionUpdate($id) {
		$model = $this->loadModel($id, 'Proyecto');

		$this->performAjaxValidation($model, 'proyecto-form');

		if (isset($_POST['Proyecto'])) {
			$model->setAttributes($_POST['Proyecto']);

			if ($model->save()) {
				$this->redirect(array('view', 'id' => $model->id));
			}
		}

		$this->render('update', array(
				'model' => $model,
				));
	}

	public function actionDelete($id) {
		if (Yii::app()->getRequest()->getIsPostRequest()) {
			$this->loadModel($id, 'Proyecto')->delete();

			if (!Yii::app()->getRequest()->getIsAjaxRequest())
				$this->redirect(array('admin'));
		} else
			throw new CHttpException(400, Yii::t('app', 'Your request is invalid.'));
	}

	public function actionIndex() {
		$dataProvider = new CActiveDataProvider('Proyecto');
		$this->render('index', array(
			'dataProvider' => $dataProvider,
		));
	}

	public function actionAdmin() {
                $session = new CHttpSession;
                $session->open();
		$model = new Proyecto('search');
		$model->unsetAttributes();

		if (isset($_GET['Proyecto'])){
			$model->setAttributes($_GET['Proyecto']);
                }

                $session['Proyecto_model_search'] = $model;
                
		$this->render('admin', array(
			'model' => $model,
		));
	}
        
        public function behaviors()
        {
            return array(
                'eexcelview'=>array(
                    'class'=>'ext.eexcelview.EExcelBehavior',
                ),
            );
        }
        
        public function actionGenerateExcel()
	{	   
             $session=new CHttpSession;
             $session->open();
             if(isset($session['Proyecto_model_search']))
               {
                $model = $session['Proyecto_model_search'];
                $model = Proyecto::model()->findAll($model->search()->criteria);
               }
               else
                 $model = Proyecto::model()->findAll();
             
             $this->toExcel($model, array('id', 'rrhh', 'centroCosto', 'nombre', 'descripcion', 'archivo', 'contrato', 'comuna', 'region'), date('Y-m-d-H-i-s'), array(), 'Excel5');
	}
        
        public function actionGeneratePdf() 
	{
             $session=new CHttpSession;
             $session->open();
             if(isset($session['Proyecto_model_search']))
               {
                $model = $session['Proyecto_model_search'];
                $model = Proyecto::model()->findAll($model->search()->criteria);
               }
               else
                 $model = Proyecto::model()->findAll();
             
             $this->toExcel($model, array('id', 'rrhh', 'centroCosto', 'nombre', 'descripcion', 'archivo', 'contrato', 'comuna', 'region'), date('Y-m-d-H-i-s'), array(), 'PDF');
	}
}

protected/modules/admin/controllers/RrhhController.php
<?php

class RrhhController extends GxController {

        public function filters() {
                return array('rights');
        }

	public function actionView($id) {
		$this->render('view', array(
			'model' => $this->loadModel($id, 'Rrhh'),
		));
	}
        
        public function actionEditable()
        {
            Yii::import('ext.x-editable.EditableSaver'); //or you can add import 'ext.editable.*' to config
            $es = new EditableSaver('Rrhh');  // 'User' is classname of model to be updated
            $es->update();
        }

	public function actionCreate() {
		$model = new Rrhh;

		$this->performAjaxValidation($model, 'rrhh-form');

		if (isset($_POST['Rrhh'])) {
			$model->setAttributes($_POST['Rrhh']);

			if ($model->save()) {
				if (Yii::app()->getRequest()->getIsAjaxRequest())
					Yii::app()->end();
				else
					$this->redirect(array('view', 'id' => $model->id));
			}
		}

		$this->render('create', array( 'model' => $model));
	}

	public function actionUpdate($id) {
		$model = $this->loadModel($id, 'Rrhh');

		$this->performAjaxValidation($model, 'rrhh-form');

		if (isset($_POST['Rrhh'])) {
			$model->setAttributes($_POST['Rrhh']);

			if ($model->save()) {
				$this->redirect(array('view', 'id' => $model->id));
			}
		}

		$this->render('update', array(
				'model' => $model,
				));
	}

	public function actionDelete($id) {
		if (Yii::app()->getRequest()->getIsPostRequest()) {
			$this->loadModel($id, 'Rrhh')->delete();

			if (!Yii::app()->getRequest()->getIsAjaxRequest())
				$this->redirect(array('admin'));
		} else
			throw new CHttpException(400, Yii::t('app', 'Your request is invalid.'));
	}

	public function actionIndex() {
		$dataProvider = new CActiveDataProvider('Rrhh');
		$this->render('index', array(
			'dataProvider' => $dataProvider,
		));
	}

	public function actionAdmin() {
                $session = new CHttpSession;
                $session->open();
		$model = new Rrhh('search');
		$model->unsetAttributes();

		if (isset($_GET['Rrhh'])){
			$model->setAttributes($_GET['Rrhh']);
                }

                $session['Rrhh_model_search'] = $model;
                
		$this->render('admin', array(
			'model' => $model,
		));
	}
        
        public function behaviors()
        {
            return array(
                'eexcelview'=>array(
                    'class'=>'ext.eexcelview.EExcelBehavior',
                ),
            );
        }
        
        public function actionGenerateExcel()
	{	   
             $session=new CHttpSession;
             $session->open();
             if(isset($session['Rrhh_model_search']))
               {
                $model = $session['Rrhh_model_search'];
                $model = Rrhh::model()->findAll($model->search()->criteria);
               }
               else
                 $model = Rrhh::model()->findAll();
             
             $this->toExcel($model, array('id', 'rut', 'nombres', 'apellidos', 'sexo', 'fecha_nacimiento', 'direccion', 'telefono', 'celular', 'email'), date('Y-m-d-H-i-s'), array(), 'Excel5');
	}
        
        public function actionGeneratePdf() 
	{
             $session=new CHttpSession;
             $session->open();
             if(isset($session['Rrhh_model_search']))
               {
                $model = $session['Rrhh_model_search'];
                $model = Rrhh::model()->findAll($model->search()->criteria);
               }
               else
                 $model = Rrhh::model()->findAll();
             
             $this->toExcel($model, array('id', 'rut', 'nombres', 'apellidos', 'sexo', 'fecha_nacimiento', 'direccion', 'telefono', 'celular', 'email'), date('Y-m-d-H-i-s'), array(), 'PDF');
	}
}

protected/modules/admin/views/proyecto/_admin.php
<?php

$this->widget('bootstrap.widgets.TbGridView', array(
	'type' => 'striped bordered',
	'dataProvider' => $model->all(),
	'template' => "{items}",
	'columns' => array(
		array(
			'class' => 'editable.EditableColumn',
			'name' => 'nombre',
			'sortable'=>true,
			'editable' => array(
				'url' => $this->createUrl('proyecto/editable'),
				'placement' => 'right',
				'inputclass' => 'span3',
                            'type'=>'text',
                            
			)
		),
		array(
			'class' => 'editable.EditableColumn',
			'name' => 'descripcion',
			'sortable'=>true,
			'editable' => array(
				'url' => $this->createUrl('proyecto/editable'),
				'placement' => 'right',
				'inputclass' => 'span3',
                            'type'=>'textarea',
                            
			)
		),
            'archivo',
            'contrato',
            array(
			'class'=>'bootstrap.widgets.TbButtonColumn',
                        'htmlOptions'=>array('style'=>'width: 50px'),
			'template'=>'{delete}',			
				
                ),
            
            ),
));
?>

protected/modules/admin/views/proyecto/_form.php
<div class="form">

    
<?php $this->widget('ext.EChosen.EChosen', array('target' => 'select')); ?>
<?php $form = $this->beginWidget('GxActiveForm', array(
	'id' => 'proyecto-form',
	'enableAjaxValidation' => true,
));
?>

	<p class="note">
		<?php echo Yii::t('app', 'Fields with'); ?> <span class="required">*</span> <?php echo Yii::t('app', 'are required'); ?>.
	</p>

	<?php echo $form->errorSummary($model); ?>

		<div class="row">
		<?php echo $form->labelEx($model,'rrhh_id'); ?>
		<?php echo $form->dropDownList($model, 'rrhh_id', GxHtml::listDataEx(Rrhh::model()->findAllAttributes(null, true))); ?>
		<?php echo $form->error($model,'rrhh_id'); ?>
		</div><!-- row -->
		<div class="row">
		<?php echo $form->labelEx($model,'centro_costo_id'); ?>
		<?php echo $form->dropDownList($model, 'centro_costo_id', GxHtml::listDataEx(CentroCosto::model()->findAllAttributes(null, true))); ?>
		<?php echo $form->error($model,'centro_costo_id'); ?>
		</div><!-- row -->
		<div class="row">
		<?php echo $form->labelEx($model,'nombre'); ?>
		<?php echo $form->textField($model, 'nombre', array('maxlength' => 255)); ?>
		<?php echo $form->error($model,'nombre'); ?>
		</div><!-- row -->
		<div class="row">
		<?php echo $form->labelEx($model,'descripcion'); ?>
		<?php echo $form->textField($model, 'descripcion'); ?>
		<?php echo $form->error($model,'descripcion'); ?>
		</div><!-- row -->
		<div class="row">
		<?php echo $form->labelEx($model,'archivo'); ?>
		<?php echo $form->textField($model, 'archivo'); ?>
		<?php echo $form->error($model,'archivo'); ?>
		</div><!-- row -->
		<div class="row">
		<?php echo $form->labelEx($model,'contrato'); ?>
		<?php echo $form->textField($model, 'contrato'); ?>
		<?php echo $form->error($model,'contrato'); ?>
		</div><!-- row -->
		<div class="row">
		<?php echo $form->labelEx($model,'comuna'); ?>
		<?php echo $form->textField($model, 'comuna', array('maxlength' => 255)); ?>
		<?php echo $form->error($model,'comuna'); ?>
		</div><!-- row -->
		<div class="row">
		<?php echo $form->labelEx($model,'region'); ?>
		<?php echo $form->textField($model, 'region', array('maxlength' => 255)); ?>
		<?php echo $form->error($model,'region'); ?>
		</div><!-- row -->

		<label><?php echo GxHtml::encode($model->getRelationLabel('contratos')); ?></label>
		<?php echo $form->checkBoxList($model, 'contratos', GxHtml::encodeEx(GxHtml::listDataEx(Contrato::model()->findAllAttributes(null, true)), false, true)); ?>
		<label><?php echo GxHtml::encode($model->getRelationLabel('emisions')); ?></label>
		<?php echo $form->checkBoxList($model, 'emisions', GxHtml::encodeEx(GxHtml::listDataEx(Emision::model()->findAllAttributes(null, true)), false, true)); ?>
		<label><?php echo GxHtml::encode($model->getRelationLabel('ingresos')); ?></label>
		<?php echo $form->checkBoxList($model, 'ingresos', GxHtml::encodeEx(GxHtml::listDataEx(Ingreso::model()->findAllAttributes(null, true)), false, true)); ?>
		<label><?php echo GxHtml::encode($model->getRelationLabel('itemRendicions')); ?></label>
		<?php echo $form->checkBoxList($model, 'itemRendicions', GxHtml::encodeEx(GxHtml::listDataEx(ItemRendicion::model()->findAllAttributes(null, true)), false, true)); ?>
		<label><?php echo GxHtml::encode($model->getRelationLabel('presupuestos')); ?></label>
		<?php echo $form->checkBoxList($model, 'presupuestos', GxHtml::encodeEx(GxHtml::listDataEx(Presupuesto::model()->findAllAttributes(null, true)), false, true)); ?>
		<label><?php echo GxHtml::encode($model->getRelationLabel('solicituds')); ?></label>
		<?php echo $form->checkBoxList($model, 'solicituds', GxHtml::encodeEx(GxHtml::listDataEx(Solicitud::model()->findAllAttributes(null, true)), false, true)); ?>
		<label><?php echo GxHtml::encode($model->getRelationLabel('itemPresupuestos')); ?></label>
		<?php echo $form->checkBoxList($model, 'itemPresupuestos', GxHtml::encodeEx(GxHtml::listDataEx(ItemPresupuesto::model()->findAllAttributes(null, true)), false, true)); ?>

<?php
echo GxHtml::submitButton(Yii::t('app', 'Save'), array('onClick' => "this.disabled=true;this.value='".Yii::t('app', 'Enviando')."';this.form.submit();"));
$this->endWidget();
?>
</div><!-- form -->

protected/modules/admin/views/proyecto/_view.php
<div class="view">

	<?php echo GxHtml::encode($data->getAttributeLabel('id')); ?>:
	<?php echo GxHtml::link(GxHtml::encode($data->id), array('view', 'id' => $data->id)); ?>
	<br />

	<?php echo GxHtml::encode($data->getAttributeLabel('rrhh_id')); ?>:
		<?php echo GxHtml::encode(GxHtml::valueEx($data->rrhh)); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('centro_costo_id')); ?>:
		<?php echo GxHtml::encode(GxHtml::valueEx($data->centroCosto)); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('nombre')); ?>:
	<?php echo GxHtml::encode($data->nombre); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('descripcion')); ?>:
	<?php echo GxHtml::encode($data->descripcion); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('archivo')); ?>:
	<?php echo GxHtml::encode($data->archivo); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('contrato')); ?>:
	<?php echo GxHtml::encode($data->contrato); ?>
	<br />
	<?php /*
	<?php echo GxHtml::encode($data->getAttributeLabel('comuna')); ?>:
	<?php echo GxHtml::encode($data->comuna); ?>
	<br />
	<?php echo GxHtml::encode($data->getAttributeLabel('region')); ?>:
	<?php echo GxHtml::encode($data->region); ?>
	<br />
	*/ ?>

</div>

protected/modules/admin/views/proyecto/view.php
<?php

$this->breadcrumbs = array(
	$model->label(2) => array('index'),
	GxHtml::valueEx($model),
);

$this->menu=array(
	array('label'=>Yii::t('app', 'List') . ' ' . $model->label(2), 'url'=>array('index')),
	array('label'=>Yii::t('app', 'Create') . ' ' . $model->label(), 'url'=>array('create')),
	array('label'=>Yii::t('app', 'Update') . ' ' . $model->label(), 'url'=>array('update', 'id' => $model->id)),
	array('label'=>Yii::t('app', 'Delete') . ' ' . $model->label(), 'url'=>'#', 'linkOptions' => array('submit' => array('delete', 'id' => $model->id), 'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>Yii::t('app', 'Manage') . ' ' . $model->label(2), 'url'=>array('admin')),
);
?>

<h1><?php echo Yii::t('app', 'View') . ' ' . GxHtml::encode($model->label()) . ' ' . GxHtml::encode(GxHtml::valueEx($model)); ?></h1>

<?php $this->widget('bootstrap.widgets.TbDetailView', array(
	'data' => $model,
	'attributes' => array(
'id',
array(
			'name' => 'rrhh',
			'type' => 'raw',
			'value' => $model->rrhh !== null ? GxHtml::link(GxHtml::encode(GxHtml::valueEx($model->rrhh)), array('rrhh/view', 'id' => GxActiveRecord::extractPkValue($model->rrhh, true))) : null,
			),
array(
			'name' => 'centroCosto',
			'type' => 'raw',
			'value' => $model->centroCosto !== null ? GxHtml::link(GxHtml::encode(GxHtml::valueEx($model->centroCosto)), array('centroCosto/view', 'id' => GxActiveRecord::extractPkValue($model->centroCosto, true))) : null,
			),
'nombre',
'descripcion',
'archivo',
'contrato',
'comuna',
'region',
	),
)); ?>

<h2><?php echo GxHtml::encode($model->getRelationLabel('contratos')); ?></h2>
<?php
	echo GxHtml::openTag('ul');
	foreach($model->contratos as $relatedModel) {
		echo GxHtml::openTag('li');
		echo GxHtml::link(GxHtml::encode(GxHtml::valueEx($relatedModel)), array('contrato/view', 'id' => GxActiveRecord::extractPkValue($relatedModel, true)));
		echo GxHtml::closeTag('li');
	}
	echo GxHtml::closeTag('ul');
?><h2><?php echo GxHtml::encode($model->getRelationLabel('emisions')); ?></h2>
<?php
	echo GxHtml::openTag('ul');
	foreach($model->emisions as $relatedModel) {
		echo GxHtml::openTag('li');
		echo GxHtml::link(GxHtml::encode(GxHtml::valueEx($relatedModel)), array('emision/view', 'id' => GxActiveRecord::extractPkValue($relatedModel, true)));
		echo GxHtml::closeTag('li');
	}
	echo GxHtml::closeTag('ul');
?><h2><?php echo GxHtml::encode($model->getRelationLabel('ingresos')); ?></h2>
<?php
	echo GxHtml::openTag('ul');
	foreach($model->ingresos as $relatedModel) {
		echo GxHtml::openTag('li');
		echo GxHtml::link(GxHtml::encode(GxHtml::valueEx($relatedModel)), array('ingreso/view', 'id' => GxActiveRecord::extractPkValue($relatedModel, true)));
		echo GxHtml::closeTag('li');
	}
	echo GxHtml::closeTag('ul');
?><h2><?php echo GxHtml::encode($model->getRelationLabel('itemRendicions')); ?></h2>
<?php
	echo GxHtml::openTag('ul');
	foreach($model->itemRendicions as $relatedModel) {
		echo GxHtml::openTag('li');
		echo GxHtml::link(GxHtml::encode(GxHtml::valueEx($relatedModel)), array('itemRendicion/view', 'id' => GxActiveRecord::extractPkValue($relatedModel, true)));
		echo GxHtml::closeTag('li');
	}
	echo GxHtml::closeTag('ul');
?><h2><?php echo GxHtml::encode($model->getRelationLabel('presupuestos')); ?></h2>
<?php
	echo GxHtml::openTag('ul');
	foreach($model->presupuestos as $relatedModel) {
		echo GxHtml::openTag('li');
		echo GxHtml::link(GxHtml::encode(GxHtml::valueEx($relatedModel)), array('presupuesto/view', 'id' => GxActiveRecord::extractPkValue($relatedModel, true)));
		echo GxHtml::closeTag('li');
	}
	echo GxHtml::closeTag('ul');
?><h2><?php echo GxHtml::encode($model->getRelationLabel('solicituds')); ?></h2>
<?php
	echo GxHtml::openTag('ul');
	foreach($model->solicituds as $relatedModel) {
		echo GxHtml::openTag('li');
		echo GxHtml::link(GxHtml::encode(GxHtml::valueEx($relatedModel)), array('solicitud/view', 'id' => GxActiveRecord::extractPkValue($relatedModel, true)));
		echo GxHtml::closeTag('li');
	}
	echo GxHtml::closeTag('ul');
?><h2><?php echo GxHtml::encode($model->getRelationLabel('itemPresupuestos')); ?></h2>
<?php
	echo GxHtml::openTag('ul');
	foreach($model->itemPresupuestos as $relatedModel) {
		echo GxHtml::openTag('li');
		echo GxHtml::link(GxHtml::encode(GxHtml::valueEx($relatedModel)), array('itemPresupuesto/view', 'id' => GxActiveRecord::extractPkValue($relatedModel, true)));
		echo GxHtml::closeTag('li');
	}
	echo GxHtml::closeTag('ul');
?>