protected/models/Factura.php
<?php

Yii::import('application.models._base.BaseFactura');

class Factura extends BaseFactura
{
        
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}
        
        public static function representingColumn() {
		return 'numero_factura';
	}
        
        public function misFacturas($id) {
		$criteria = new CDbCriteria;
		$criteria->compare('cliente_id', $id);
		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        'pagination'=>false,
		));
	}
       
}

protected/controllers/ClienteController.php
<?php

class ClienteController extends GxController {


	public function actionView($id) {
		$this->render('view', array(
			'model' => $this->loadModel($id, 'Cliente'),
		));
	}

        public function actionVer($id) {
            $model = $this->loadModel($id, 'Cliente');
            $model_factura = new Factura;
            $model_factura=$model_factura->misFacturas($id);
            
		$this->render('ver', array(
			'model' => $model,
                        'model_factura' => $model_factura,
		));
	}
        
	public function actionCreate() {
		$model = new Cliente;
                $session=Yii::app()->getSession();
                $id_user=$session['_id'];
                $model->user_id=$id_user;
		$this->performAjaxValidation($model, 'cliente-form');

		if (isset($_POST['Cliente'])) {
			$model->setAttributes($_POST['Cliente']);

			if ($model->save()) {
				if (Yii::app()->getRequest()->getIsAjaxRequest())
					Yii::app()->end();
				else
					$this->redirect(array('view', 'id' => $model->id));
			}
		}

		$this->render('create', array( 'model' => $model));
	}
        
        public function actionCrear() {
		$model = new Cliente;
                $model->user_id=User::model()->findByPk(Yii::app()->user->id)->id; 
		$this->performAjaxValidation($model, 'cliente-form');

		if (isset($_POST['Cliente'])) {
			$model->setAttributes($_POST['Cliente']);

			if ($model->save()) {
				if (Yii::app()->getRequest()->getIsAjaxRequest())
					Yii::app()->end();
				else
					$this->redirect(array('verTodos', 'id' => $model->id));
			}
		}

		$this->render('crear', array( 'model' => $model));
	}

	public function actionUpdate($id) {
		$model = $this->loadModel($id, 'Cliente');

		$this->performAjaxValidation($model, 'cliente-form');

		if (isset($_POST['Cliente'])) {
			$model->setAttributes($_POST['Cliente']);

			if ($model->save()) {
				$this->redirect(array('view', 'id' => $model->id));
			}
		}

		$this->render('update', array(
				'model' => $model,
				));
	}
        
        public function actionActualizar($id) {
		$model = $this->loadModel($id, 'Cliente');

		$this->performAjaxValidation($model, 'cliente-form');

		if (isset($_POST['Cliente'])) {
			$model->setAttributes($_POST['Cliente']);

			if ($model->save()) {
				$this->redirect(array('verTodos', 'id' => $model->id));
			}
		}

		$this->render('actualizar', array(
				'model' => $model,
				));
	}
        
	public function actionDelete($id) {
		if (Yii::app()->getRequest()->getIsPostRequest()) {
			$this->loadModel($id, 'Cliente')->delete();

			if (!Yii::app()->getRequest()->getIsAjaxRequest())
				$this->redirect(array('admin'));
		} else
			throw new CHttpException(400, Yii::t('app', 'Your request is invalid.'));
	}
        
        public function actionEliminar($id) {
		if (Yii::app()->getRequest()->getIsPostRequest()) {
			$this->loadModel($id, 'Cliente')->delete();

			if (!Yii::app()->getRequest()->getIsAjaxRequest())
				$this->redirect(array('verTodos'));
		} else
			throw new CHttpException(400, Yii::t('app', 'Your request is invalid.'));
	}

	public function actionIndex() {
		$dataProvider = new CActiveDataProvider('Cliente');
		$this->render('index', array(
			'dataProvider' => $dataProvider,
		));
	}

	public function actionAdmin() {
		$model = new Cliente('search');
		$model->unsetAttributes();

		if (isset($_GET['Cliente']))
			$model->setAttributes($_GET['Cliente']);

		$this->render('admin', array(
			'model' => $model,
		));
	}
        
        public function actionVerTodos() {
		$model = new Cliente('search');
		$model->unsetAttributes();

		if (isset($_GET['Cliente']))
			$model->setAttributes($_GET['Cliente']);

		$this->render('verTodos', array(
			'model' => $model,
		));
	}

}

protected/controllers/DetalleController.php
<?php

class DetalleController extends GxController {


        public function calcularIva($id, $total){
            $model_factura = $this->loadModel($id, 'Factura');
            $model_factura->total = $model_factura->total + $total;  
            $model_factura->valor_neto = round($model_factura->total / 1.19);
            $model_factura->iva = round($model_factura->valor_neto * 0.19);
            $model_factura->valor_neto = $model_factura->total - $model_factura->iva;
            $model_factura->save(false);
        }
        
	public function actionView($id) {
		$this->render('view', array(
			'model' => $this->loadModel($id, 'Detalle'),
		));
	}
        
        public function actionVer($id) {
		$this->render('ver', array(
			'model' => $this->loadModel($id, 'Detalle'),
		));
	}

	public function actionCreate() {
		$model = new Detalle;

		$this->performAjaxValidation($model, 'detalle-form');

		if (isset($_POST['Detalle'])) {
			$model->setAttributes($_POST['Detalle']);

			if ($model->save()) {
				if (Yii::app()->getRequest()->getIsAjaxRequest())
					Yii::app()->end();
				else
					$this->redirect(array('view', 'id' => $model->id));
			}
		}

		$this->render('create', array( 'model' => $model));
	}
        
        
        public function actionCrear($id) {
		$model = new Detalle;
                $model->factura_id = $id;
                                      
		$this->performAjaxValidation($model, 'detalle-form');

		if (isset($_POST['Detalle'])) {
			$model->setAttributes($_POST['Detalle']);
                        $model->total = $model->cantidad * $model->precio_unit;         
                        $this->calcularIva($id, $model->total);
                                
			if ($model->save()) {
				if (Yii::app()->getRequest()->getIsAjaxRequest())
					Yii::app()->end();
				else
					$this->redirect(array('factura/ver', 'id' => $id));
			}
		}

		$this->render('crear', array( 'model' => $model));
	}

	public function actionUpdate($id) {
		$model = $this->loadModel($id, 'Detalle');
                
		$this->performAjaxValidation($model, 'detalle-form');

		if (isset($_POST['Detalle'])) {
			$model->setAttributes($_POST['Detalle']);
                        $model->total = $model->cantidad * $model->precio_unit;         
                        $this->calcularIva($id, $model->total);
			if ($model->save()) {
				$this->redirect(array('view', 'id' => $model->id));
			}
		}

		$this->render('update', array(
				'model' => $model,
				));
	}
        
        public function actionActualizar($id) {
		$model = $this->loadModel($id, 'Detalle');
                $total_antiguo = $model->total;
		$this->performAjaxValidation($model, 'detalle-form');

		if (isset($_POST['Detalle'])) {
			$model->setAttributes($_POST['Detalle']);
                                             
                        $model->total = $model->cantidad * $model->precio_unit;
                        $model_factura = $this->loadModel($model->factura_id, 'Factura');
                        $model_factura->total = $model_factura->total - $total_antiguo;
                        $model_factura->save(false);
                        $this->calcularIva($model->factura_id, $model->total);
                        
			if ($model->save(false)) {
				$this->redirect(array('factura/ver', 'id' => $model->factura_id));
			}
		}

		$this->render('actualizar', array(
				'model' => $model,
				));
	}

	public function actionDelete($id) {
		if (Yii::app()->getRequest()->getIsPostRequest()) {
			$this->loadModel($id, 'Detalle')->delete();

			if (!Yii::app()->getRequest()->getIsAjaxRequest())
				$this->redirect(array('admin'));
		} else
			throw new CHttpException(400, Yii::t('app', 'Your request is invalid.'));
	}
        
        public function actionEliminar($id) {
		if (Yii::app()->getRequest()->getIsPostRequest()) {
			$model = $this->loadModel($id, 'Detalle');
                        $id = $model->factura_id;
                        $model_factura = $this->loadModel($model->factura_id, 'Factura');
                        $model_factura->total = $model_factura->total - $model->total;
                        //$model->factura->total = $model->factura->total - $model->total;
                                                                       
                        $model_factura->save(false);
                        $this->calcularIva($model->factura_id, 0);
                        $model->delete();
                        $this->redirect(array('factura/ver','id' => $id));

			if (!Yii::app()->getRequest()->getIsAjaxRequest())
				$this->redirect(array('factura/ver','id' => $id));
		} else
			throw new CHttpException(400, Yii::t('app', 'Your request is invalid.'));
	}

	public function actionIndex() {
		$dataProvider = new CActiveDataProvider('Detalle');
		$this->render('index', array(
			'dataProvider' => $dataProvider,
		));
	}

	public function actionAdmin() {
		$model = new Detalle('search');
		$model->unsetAttributes();

		if (isset($_GET['Detalle']))
			$model->setAttributes($_GET['Detalle']);

		$this->render('admin', array(
			'model' => $model,
		));
	}
        
        public function actionVerTodos() {
		$model = new Detalle('search');
		$model->unsetAttributes();

		if (isset($_GET['Detalle']))
			$model->setAttributes($_GET['Detalle']);

		$this->render('verTodos', array(
			'model' => $model,
		));
	}

}

protected/controllers/FacturaController.php
<?php

class FacturaController extends GxController {


	public function actionView($id) {
		$this->render('view', array(
			'model' => $this->loadModel($id, 'Factura'),
		));
	}
        public function actionImprimir($id){
            $this->layout="imprimir";
            $this->render('imprimir', array(
			'model' => $this->loadModel($id, 'Factura'),
		));
        }
        
        public function actionVer($id) {
		$model = $this->loadModel($id, 'Factura');
                $model_detalle = new Detalle;
                $model_detalle = $model_detalle->misDetalles($id);
                                    
		$this->render('ver', array(
			'model' => $model,
                        'model_detalle' => $model_detalle,
		));
                
	}

	public function actionCreate() {
		$model = new Factura;

		$this->performAjaxValidation($model, 'factura-form');

		if (isset($_POST['Factura'])) {
			$model->setAttributes($_POST['Factura']);

			if ($model->save()) {
				if (Yii::app()->getRequest()->getIsAjaxRequest())
					Yii::app()->end();
				else
					$this->redirect(array('view', 'id' => $model->id));
			}
		}

		$this->render('create', array( 'model' => $model));
	}
        
        public function actionCrear() {
		$model = new Factura;

		$this->performAjaxValidation($model, 'factura-form');

		if (isset($_POST['Factura'])) {
			$model->setAttributes($_POST['Factura']);

			if ($model->save()) {
				if (Yii::app()->getRequest()->getIsAjaxRequest())
					Yii::app()->end();
				else
					$this->redirect(array('ver', 'id' => $model->id));
			}
		}

		$this->render('crear', array( 'model' => $model));
	}

	public function actionUpdate($id) {
		$model = $this->loadModel($id, 'Factura');

		$this->performAjaxValidation($model, 'factura-form');

		if (isset($_POST['Factura'])) {
			$model->setAttributes($_POST['Factura']);

			if ($model->save()) {
				$this->redirect(array('view', 'id' => $model->id));
			}
		}

		$this->render('update', array(
				'model' => $model,
				));
	}
        
        public function actionActualizar($id) {
		$model = $this->loadModel($id, 'Factura');

		$this->performAjaxValidation($model, 'factura-form');

		if (isset($_POST['Factura'])) {
			$model->setAttributes($_POST['Factura']);

			if ($model->save()) {
				$this->redirect(array('verTodos', 'id' => $model->id));
			}
		}

		$this->render('actualizar', array(
				'model' => $model,
				));
	}

	public function actionDelete($id) {
		if (Yii::app()->getRequest()->getIsPostRequest()) {
			$this->loadModel($id, 'Factura')->delete();

			if (!Yii::app()->getRequest()->getIsAjaxRequest())
				$this->redirect(array('admin'));
		} else
			throw new CHttpException(400, Yii::t('app', 'Your request is invalid.'));
	}
        
        public function actionEliminar($id) {
		if (Yii::app()->getRequest()->getIsPostRequest()) {
			$this->loadModel($id, 'Factura')->delete();

			if (!Yii::app()->getRequest()->getIsAjaxRequest())
				$this->redirect(array('verTodos'));
		} else
			throw new CHttpException(400, Yii::t('app', 'Your request is invalid.'));
	}

	public function actionIndex() {
		$dataProvider = new CActiveDataProvider('Factura');
		$this->render('index', array(
			'dataProvider' => $dataProvider,
		));
	}

	public function actionAdmin() {
		$model = new Factura('search');
		$model->unsetAttributes();

		if (isset($_GET['Factura']))
			$model->setAttributes($_GET['Factura']);

		$this->render('admin', array(
			'model' => $model,
		));
	}
        
        public function actionVerTodos() {
		$model = new Factura('search');
		$model->unsetAttributes();

		if (isset($_GET['Factura']))
			$model->setAttributes($_GET['Factura']);

		$this->render('verTodos', array(
			'model' => $model,
		));
	}

}

protected/views/factura/_crear.php
<div class="form">

<?php $this->widget('ext.EChosen.EChosen', array('target' => 'select')); ?>
<?php $form = $this->beginWidget('GxActiveForm', array(
	'id' => 'factura-form',
	'enableAjaxValidation' => true,
));
?>

	<p class="note">
		<?php echo Yii::t('app', 'Fields with'); ?> <span class="required">*</span> <?php echo Yii::t('app', 'are required'); ?>.
	</p>

	<?php echo $form->errorSummary($model); ?>
        
                <div class="row">
		<?php echo $form->labelEx($model,'numero_factura'); ?>
		<?php echo $form->textField($model, 'numero_factura'); ?>
		<?php echo $form->error($model,'numero_factura'); ?>
		</div><!-- row -->
		<div class="row">
		<?php echo $form->labelEx($model,'cliente_id'); ?>
		<?php echo $form->dropDownList($model, 'cliente_id', GxHtml::listDataEx(Cliente::model()->findAll(array('order'=>'rut')))); ?>
		<?php echo $form->error($model,'cliente_id'); ?>
		</div><!-- row -->
		<div class="row">
		<?php echo $form->labelEx($model,'fecha'); ?>
		<?php $form->widget('zii.widgets.jui.CJuiDatePicker', array(
			'model' => $model,
			'attribute' => 'fecha',
			'value' => $model->fecha,
                        'language' => Yii::app()->language,    
			'options' => array(
				'showButtonPanel' => true,
                                'changeMonth' => true,
				'changeYear' => true,
				'dateFormat' => 'yy-mm-dd',
				),
			));
; ?>
		<?php echo $form->error($model,'fecha'); ?>
		</div><!-- row -->
		<div class="row">
		<?php echo $form->labelEx($model,'guia_despacho'); ?>
		<?php echo $form->textField($model, 'guia_despacho', array('maxlength' => 45)); ?>
		<?php echo $form->error($model,'guia_despacho'); ?>
		</div><!-- row -->
		<div class="row">
		<?php echo $form->labelEx($model,'condiciones_venta'); ?>
		<?php echo $form->dropDownList($model, 'condiciones_venta', array('CONTADO' => 'CONTADO', 'CREDITO' => 'CREDITO')); ?>
		<?php echo $form->error($model,'condiciones_venta'); ?>
		</div><!-- row -->

<?php
echo GxHtml::submitButton(Yii::t('app', 'Save'));
$this->endWidget();
?>
</div><!-- form -->

protected/views/factura/_form.php
<div class="form">


<?php $form = $this->beginWidget('GxActiveForm', array(
	'id' => 'factura-form',
	'enableAjaxValidation' => true,
));
?>

	<p class="note">
		<?php echo Yii::t('app', 'Fields with'); ?> <span class="required">*</span> <?php echo Yii::t('app', 'are required'); ?>.
	</p>

	<?php echo $form->errorSummary($model); ?>

		<div class="row">
		<?php echo $form->labelEx($model,'cliente_id'); ?>
		<?php echo $form->dropDownList($model, 'cliente_id', GxHtml::listDataEx(Cliente::model()->findAllAttributes(null, true))); ?>
		<?php echo $form->error($model,'cliente_id'); ?>
		</div><!-- row -->
		<div class="row">
		<?php echo $form->labelEx($model,'fecha'); ?>
		<?php $form->widget('zii.widgets.jui.CJuiDatePicker', array(
			'model' => $model,
			'attribute' => 'fecha',
			'value' => $model->fecha,
                        'language' => Yii::app()->language,    
			'options' => array(
				'showButtonPanel' => true,
                                'changeMonth' => true,
				'changeYear' => true,
				'dateFormat' => 'yy-mm-dd',
				),
			));
; ?>
		<?php echo $form->error($model,'fecha'); ?>
		</div><!-- row -->
		<div class="row">
		<?php echo $form->labelEx($model,'guia_despacho'); ?>
		<?php echo $form->textField($model, 'guia_despacho', array('maxlength' => 45)); ?>
		<?php echo $form->error($model,'guia_despacho'); ?>
		</div><!-- row -->
		<div class="row">
		<?php echo $form->labelEx($model,'condiciones_venta'); ?>
		<?php echo $form->textField($model, 'condiciones_venta', array('maxlength' => 45)); ?>
		<?php echo $form->error($model,'condiciones_venta'); ?>
		</div><!-- row -->
		<div class="row">
		<?php echo $form->labelEx($model,'valor_neto'); ?>
		<?php echo $form->textField($model, 'valor_neto'); ?>
		<?php echo $form->error($model,'valor_neto'); ?>
		</div><!-- row -->
		<div class="row">
		<?php echo $form->labelEx($model,'iva'); ?>
		<?php echo $form->textField($model, 'iva'); ?>
		<?php echo $form->error($model,'iva'); ?>
		</div><!-- row -->
		<div class="row">
		<?php echo $form->labelEx($model,'total'); ?>
		<?php echo $form->textField($model, 'total'); ?>
		<?php echo $form->error($model,'total'); ?>
		</div><!-- row -->
		<div class="row">
		<?php echo $form->labelEx($model,'numero_factura'); ?>
		<?php echo $form->textField($model, 'numero_factura'); ?>
		<?php echo $form->error($model,'numero_factura'); ?>
		</div><!-- row -->

		<label><?php echo GxHtml::encode($model->getRelationLabel('detalles')); ?></label>
		<?php echo $form->checkBoxList($model, 'detalles', GxHtml::encodeEx(GxHtml::listDataEx(Detalle::model()->findAllAttributes(null, true)), false, true)); ?>

<?php
echo GxHtml::submitButton(Yii::t('app', 'Save'));
$this->endWidget();
?>
</div><!-- form -->

protected/views/factura/actualizar.php
<?php

$this->breadcrumbs = array(
	$model->label(2) => array('verTodos'),
	GxHtml::valueEx($model) => array('ver', 'id' => GxActiveRecord::extractPkValue($model, true)),
	Yii::t('app', 'Update'),
);

$this->menu = array(
	array('label'=>Yii::t('app', 'Back'), 'url'=>Yii::app()->request->urlReferrer),
);
?>

<h1><?php echo Yii::t('app', 'Update') . ' ' . GxHtml::encode($model->label()) . ' ' . GxHtml::encode(GxHtml::valueEx($model)); ?></h1>

<?php
$this->renderPartial('_crear', array(
		'model' => $model));
?>

protected/views/factura/ver.php
<?php

$this->breadcrumbs = array(
	$model->label(2) => array('verTodos'),
	GxHtml::valueEx($model),
);

$this->menu=array(
	array('label'=>Yii::t('app', 'Create') . ' ' . $model->label(), 'url'=>array('crear')),
	array('label'=>Yii::t('app', 'Update') . ' ' . $model->label(), 'url'=>array('actualizar', 'id' => $model->id)),
	array('label'=>Yii::t('app', 'Delete') . ' ' . $model->label(), 'url'=>'#', 'linkOptions' => array('submit' => array('eliminar', 'id' => $model->id), 'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>Yii::t('app', 'Manage') . ' ' . $model->label(2), 'url'=>array('verTodos')),
        array('label'=>Yii::t('app', 'Imprimir') . ' ' . $model->label(), 'url'=>array('imprimir', 'id' => $model->id)),
        array('label'=>Yii::t('app', 'Crear Detalle'), 'url'=>array('detalle/crear', 'id' => $model->id)),
	array('label'=>Yii::t('app', 'Back'), 'url'=>Yii::app()->request->urlReferrer),
);
?>

<h1><?php echo Yii::t('app', 'View') . ' ' . GxHtml::encode($model->label()) . ' ' . GxHtml::encode(GxHtml::valueEx($model)); ?></h1>

<?php $this->widget('bootstrap.widgets.TbDetailView', array(
	'data' => $model,
	'attributes' => array(

            array(
                                    'name' => 'cliente',
                                    'type' => 'raw',
                                    'value' => $model->cliente !== null ? GxHtml::link(GxHtml::encode(GxHtml::valueEx($model->cliente)), array('cliente/ver', 'id' => GxActiveRecord::extractPkValue($model->cliente, true))) : null,
                                    ),
            'fecha',
            'guia_despacho',
            'condiciones_venta',
            array(
                'name'=>'valor_neto',
                'type'=>'raw',
                'value'=>Yii::app()->format->formatNumber($model->valor_neto)
                ),
            array(
                'name'=>'iva',
                'type'=>'raw',
                'value'=>Yii::app()->format->formatNumber($model->iva)
                ),
            array(
                'name'=>'total',
                'type'=>'raw',
                'value'=>Yii::app()->format->formatNumber($model->total)
                ),
                    ),
            )); ?>

<?php
$this->widget('bootstrap.widgets.TbGridView', array(
    'type'=>'striped bordered',
    'dataProvider' => $model_detalle,
    'enableSorting'=>false,
    'template'=> '{summary}{pager}{items}{pager}',
    'columns' => array(
		'cantidad',
                'servicio',
                
                array(
                'name'=>'precio_unit',
                'type'=>'raw',
                'value'=>'Yii::app()->format->formatNumber($data->precio_unit)'
                ),
        
                array(
                'name'=>'total',
                'type'=>'raw',
                'value'=>'Yii::app()->format->formatNumber($data->total)'
                ),
                
                array(
			'class'=>'bootstrap.widgets.TbButtonColumn',
                        'htmlOptions'=>array('style'=>'width: 60px'),
			'template'=>'{view} {update} {delete}',
			'buttons'=>array(
				'view' => array(
					'label'=>'Ver Detalle',
					'url'=>'Yii::app()->createUrl("detalle/ver", array("id"=>$data->id))',
				),
				'update' => array(
					'label'=>'Actualizar Detalle',
					'url'=>'Yii::app()->createUrl("detalle/actualizar", array("id"=>$data->id))',
				),
                                'delete' => array(
					'label'=>'Eliminar Detalle',
					'url'=>'Yii::app()->createUrl("detalle/eliminar", array("id"=>$data->id))',
				),
			),
				
                ),
    ),
));?>

protected/views/factura/verTodos.php
<?php

$this->breadcrumbs = array(
	Yii::t('app', 'Manage'),
);

$this->menu = array(
		array('label'=>Yii::t('app', 'Create') . ' ' . $model->label(), 'url'=>array('crear')),
	);

Yii::app()->clientScript->registerScript('search', "
$('.search-button').click(function(){
	$('.search-form').toggle();
	return false;
});
$('.search-form form').submit(function(){
	$.fn.yiiGridView.update('factura-grid', {
		data: $(this).serialize()
	});
	return false;
});
");
?>

<h1><?php echo Yii::t('app', 'Manage') . ' ' . GxHtml::encode($model->label(2)); ?></h1>

<?php echo GxHtml::link(Yii::t('app', 'Advanced Search'), '#', array('class' => 'search-button')); ?>
<div class="search-form">
<?php $this->renderPartial('_search', array(
	'model' => $model,
)); ?>
</div><!-- search-form -->

<?php $this->widget('bootstrap.widgets.TbGridView', array(
	'id' => 'factura-grid',
	'dataProvider' => $model->search(),
	'filter' => $model,
        'type'=>'striped bordered condensed',
        'template'=>"{summary}{items}{pager}",
	'columns' => array(
		'numero_factura',
		array(
				'name'=>'cliente_id',
				'value'=>'GxHtml::valueEx($data->cliente)',
				'filter'=>GxHtml::listDataEx(Cliente::model()->findAllAttributes(null, true)),
				),
		'fecha',
		'guia_despacho',
		'condiciones_venta',
		array(
			'class'=>'bootstrap.widgets.TbButtonColumn',
                        'htmlOptions'=>array('style'=>'width: 50px'),
			'template'=>'{view}{update}{delete}',
			'buttons'=>array(
				'view' => array(
					'label'=>'Ver Factura',
					'url'=>'Yii::app()->createUrl("factura/ver", array("id"=>$data->id))',
				),
                                'update' => array(
					'label'=>'Actualizar Factura',
					'url'=>'Yii::app()->createUrl("factura/actualizar", array("id"=>$data->id))',
				),
                                'delete' => array(
					'label'=>'Eliminar Factura',
					'url'=>'Yii::app()->createUrl("factura/eliminar", array("id"=>$data->id))',
				),
				
			),
				
                ),
	),
)); ?>

protected/views/factura/view.php
<?php

$this->breadcrumbs = array(
	$model->label(2) => array('index'),
	GxHtml::valueEx($model),
);

$this->menu=array(
	array('label'=>Yii::t('app', 'List') . ' ' . $model->label(2), 'url'=>array('index')),
	array('label'=>Yii::t('app', 'Create') . ' ' . $model->label(), 'url'=>array('create')),
	array('label'=>Yii::t('app', 'Update') . ' ' . $model->label(), 'url'=>array('update', 'id' => $model->id)),
	array('label'=>Yii::t('app', 'Delete') . ' ' . $model->label(), 'url'=>'#', 'linkOptions' => array('submit' => array('delete', 'id' => $model->id), 'confirm'=>'Are you sure you want to delete this item?')),
	array('label'=>Yii::t('app', 'Manage') . ' ' . $model->label(2), 'url'=>array('admin')),
);
?>

<h1><?php echo Yii::t('app', 'View') . ' ' . GxHtml::encode($model->label()) . ' ' . GxHtml::encode(GxHtml::valueEx($model)); ?></h1>

<?php $this->widget('zii.widgets.CDetailView', array(
	'data' => $model,
	'attributes' => array(
'id',
array(
			'name' => 'cliente',
			'type' => 'raw',
			'value' => $model->cliente !== null ? GxHtml::link(GxHtml::encode(GxHtml::valueEx($model->cliente)), array('cliente/view', 'id' => GxActiveRecord::extractPkValue($model->cliente, true))) : null,
			),
'fecha',
'guia_despacho',
'condiciones_venta',
'valor_neto',
'iva',
'total',
'numero_factura',
	),
)); ?>

<h2><?php echo GxHtml::encode($model->getRelationLabel('detalles')); ?></h2>
<?php
	echo GxHtml::openTag('ul');
	foreach($model->detalles as $relatedModel) {
		echo GxHtml::openTag('li');
		echo GxHtml::link(GxHtml::encode(GxHtml::valueEx($relatedModel)), array('detalle/view', 'id' => GxActiveRecord::extractPkValue($relatedModel, true)));
		echo GxHtml::closeTag('li');
	}
	echo GxHtml::closeTag('ul');
?>